### ISSUE TITLE
Missing tags argument

### ISSUE THREAD

**Issue by ge1st** [ojongerius/terraform-provider-datadog#78]
Hi guys, congrats on getting this merged in TF core. Let me know if I should report this there instead. I thought this would be more visible here.

Looks like you missed the `tags` argument. I assume since you deprecated the wrapper monitor types and it was being used to populate the query string before. 

From the API docs:

```
tags [optional, default=empty list]
A list of tags to associate with your monitor. This can help you categorize and filter monitors.
```

So not the tags to use in the query string but tags to tag the monitor with.

I'm not currently using this but thought I should raise it.

thanks

**Comment by ojongerius** [comment]
Support for tags in the original monitors was used to generate queries, that turned out to be too involved / error and was dropped for just letting users specify a query including tags.

I would like support for the monitor tag too, our list of monitors in growing and grouping them would be welcome!

Could you please raise this issue at Terraform, feel free to at mention me in it. I'm pretty swamped at the moment, but if no one else runs this one I could take a look.
